### ISSUE TITLE
I don't like Elnur

### ISSUE THREAD

**Issue by Tantacrul** [Eism/MuseScore#51]
### Issue type

Engraving bug

### Steps to reproduce

1. Look at Elnur

### MuseScore Version

4.0.0

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Win 11

**Comment by RomanPudashkin** [comment]
:(

**Comment by Tantacrul** [comment]
Resolved. Elnur has improved and I now like him.
